name: linting, testing, building
run-name: ${{ github.actor }} is testing production-project ğŸš€
on: 
   push:
      branches: [ master ]
      pull_request: [ master ]
jobs:
   pipeline:
      runs-on: windows-2019
      strategy:
         matrix:
            node-version: [ 16.x ]

      steps:
         -  uses: actions/checkout@v2
         -  name: Staring Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: ${{ matrix.node-version }}

         -  name: ğŸ’¡ Install modules
            run: npm install
         -  name: ğŸ§ Build production project
            run: npm run build:prod
            if: always()
         -  name: Linting typescript
            run: npm run lint:ts
            if: always()
         -  name: Linting css
            run: npm run lint:scss
            if: always()
         -  name: ğŸ” Unit testing
            run: npm run test:unit
            if: always()
         -  name: Build storybook
            run: npm run storybook:build
            if: always()
         -  name: ğŸ–¥ï¸ Screenshot testing
            run: npm run test:ui:ci
            if: always()
        