name: linting, testing, building
run-name: ${{ github.actor }} is testing production-project ğŸš€
on: 
   push:
      branches: [ master ]
      pull_request: [ master ]
jobs:
   pipeline:
      runs-on: ubuntu-latest
      strategy:
         matrix:
            node-version: [ 17.x ]

      steps:
         -  uses: actions/checkout@v2
         -  name: Staring Node.js ${{ matrix.node-version }}
            uses: actions/setup-node@v1
            with:
               node-version: ${{ matrix.node-version }}

         -  name: ğŸ’¡ install modules
            run: npm install
         -  name: ğŸ§ build production project
            run: npm run build:prod
         -  name: linting typescript
            run: npm run lint:ts
         -  name: linting css
            run: npm run lint:scss
         -  name: ğŸ” unit testing
            run: npm run test:unit
        